# SygeforCoreBundle
sygefor_core:
    batch:
        convert_type:
            semestered_training:
                class: 'SygeforCoreBundle:AbstractTraining'
        csv:
            user:
                class: 'SygeforCoreBundle:User'
                filename: 'utilisateurs.csv'
                fields:
                    username: Nom
                    email: Email
                    organization.name: Centre
            session:
                class: 'AppBundle\Entity\Session\Session'
                filename: 'session.csv'
                fields:
                    id: "Identifiant de la session"
                    training.id: "Identifiant de la formation"
                    training.name: "Intitulé de la formation"
                    name: "Intitulé de la session"
                    dateBegin: { label: "Date de début", type: "date" }
                    dateEnd: { label: "Date de fin", type: "date" }
                    datePrecisions: { label: "Précisions" }
                    schedule: { label: "Horaires" }
                    place.name: 'Lieu'
                    price: 'Tarif'
                    participations: { label: 'Formateurs', subProperty: "trainer.fullName" }
                    inscriptions: { label: 'Inscriptions', subProperty: "id" }
                    maximumNumberOfRegistrations: 'Nombre de places'
                    numberOfRegistrations: "Nombre d'inscrits"
                    numberOfParticipants: 'Nombre de présents'
                    registration: 'Inscriptions'
                    promote: {label: 'Promotion', type: 'boolean'}
                    displayOnline: {label: 'Afficher en ligne', type: 'boolean'}
                    hourNumber: "Nombre d'heures"
                    dayNumber: 'Nombre de jours'
                    reprographyCost: 'Frais de repographie'
                    otherCost: 'Autres frais'
                    subscriptionRightTaking: "Droit d'inscription"
                    otherTaking: 'Autres entrées'
            semestered_training:
                class: 'AppBundle\Model\SemesteredTraining'
                filename: 'formation.csv'
                fields:
                    training.typeLabel: { label: 'Type de formation' }
                    training.id: { label: 'Identifiant' }
                    training.name: { label: 'Intitulé' }
                    training.number: { label: 'Numéro' }
                    training.organization.name: { label: 'Centre' }
                    sessionsCount: { label: 'nombre de sessions' }
                    nextSession.id: "Identifiant de la prochaine session"
                    nextSession.dateBegin: { label: 'Prochaine', type: 'date' }
                    lastSession.id: "Identifiant de la dernière session"
                    lastSession.dateBegin: { label: 'Dernière', type: 'date' }
                    year: { label: 'Année' }
                    semester: { label: 'Semestre' }
                    training.theme: { label: 'Thème' }
                    training.program: { label: 'Programme' }
                    training.description: { label: 'Objectifs' }
                    training.teachingMethods: { label: 'Méthodes pédagogiques' }
                    training.user.username: { label: 'Assistant' }
                    training.tags: { label: 'Tags', subProperty: "name" }
                    # Internship | Long training
                    training.publicTypes: { label: 'Types de public', subProperty: "name" }
                    training.prerequisites: { label: 'Prérequis' }
                    # Long training
                    training.modules: { label: 'Modules', subProperty: "name" }
                    # Meeting
                    training.national: { label: 'National', type: 'boolean' }
            trainee:
                class: 'AppBundle\Entity\Trainee\Trainee'
                filename: 'stagiaire.csv'
                fields:
                    id: "Identifiant"
                    organization.name: "Centre"
                    createdAt: { label: "Date de création", type: "date" }
                    title: "Civilité"
                    lastName: "Nom"
                    firstName: "Prénom"
                    email: "Email"
                    phoneNumber: "Téléphone"
                    address: "Adresse"
                    zip: "Code postal"
                    city: "Ville"
                    inscriptions: { label: 'Inscriptions', subProperty: "id" }
                    publicType.name: { label: 'Type de personnel' }
                    otherPublicType: { label: 'Autre type de personnel' }
                    position: { label: 'Fonction' }
                    service: { label: 'Service' }
                    newsletter: { label: "Lettre d'information" }
            inscription:
                class: 'AppBundle\Entity\Inscription'
                filename: 'inscription.csv'
                fields:
                    id: "Identifiant"
                    trainee.organization.name: "Centre"
                    trainee.title: "Civilité"
                    trainee.lastName: "Nom"
                    trainee.firstName: "Prénom"
                    trainee.email: "Email"
                    trainee.phoneNumber: "Téléphone"
                    session.training.id: "Identifiant de la formation"
                    session.training.name: "Formation"
                    session.id: "Identifiant de la session"
                    session.name: "Intitulé de la session"
                    session.dateRange: "Dates de la session"
                    inscriptionStatus: "Statut de l'inscription"
                    motivation: "Motivation"
                    personHours: "Heures-personne"
                    presenceStatus: "Statut de présence"
                    createdAt: { label: "Date d'inscription", type: "date" }
                    disciplinary.name: { label: 'Domaine disciplinaire historisé' }
                    publicType.name: { label: 'Type de personnel historisé' }
                    otherPublicType: { label: 'Autre type de personnel historisé' }
                    position: { label: 'Fonction historisé' }
                    service: { label: 'Service historisée' }
            trainer:
                class: 'AppBundle\Entity\Trainer'
                filename: 'formateur.csv'
                fields:
                    id: "Identifiant"
                    organization.name: "Centre"
                    title: "Civilité"
                    lastName: "Nom"
                    firstName: "Prénom"
                    email: "Email"
                    phoneNumber: "Téléphone"
                    address: "Adresse"
                    zip: "Code postal"
                    city: "Ville"
                    position: "Service"
                    function: "Fonction"
                    observations: "Observations"
                    participations: { label: 'Sessions', subProperty: "session.id" }
                    isOrganization: { label: "Intervenant interne", type: "boolean" }
                    isArchived: { label: "Archivé", type: "boolean" }
                    createdAt: { label: "Date de création", type: "date" }
        mailing:
            # session dates
            stdClass:
                class: 'stdClass'
                alias: 'Classe'
                excludeFromFormType: true
                fields:
                    date: { property: date }
            organization:
                class: 'AppBundle\Entity\Organization'
                excludeFromFormType: true
                alias: 'centre'
                emailPath: 'email'
                fields:
                    nom: { property: name }
                    code: { property: code }
                    email: { property: email }
                    adresse: { property: fullAddress }
                    telephone: { property: phoneNumber }
                    site: { property: website }
            inscription:
                class: 'AppBundle\Entity\Inscription'
                emailPath: 'trainee.email'
                alias: 'inscription'
                shorcuts:
                    formateurs: { current: true, path: session.trainers, sort: nom }
                    stagiaires: { current: false, path: trainee, sort: nom }
                    dates: { current: true, path: session.datesArray }
                fields:
                    centre: { property: trainee.organization }
                    date: { property: createdAt }
                    session: { property: session }
                    stagiaire: { property: trainee }
                    statutInscription: { property: inscriptionStatus.name }
                    statutPresence: { property: presenceStatus.name }
                    motivation: { property: 'motivation' }
                    evaluationUrl: { property: 'evaluationUrl' }
            trainee:
                class: 'AppBundle\Entity\Trainee\Trainee'
                alias: 'stagiaire'
                emailPath: 'email'
                fields:
                    centre: {property: organization}
                    # PersonTrait
                    civilite: { property: title }
                    nomComplet: { property: fullName }
                    nom: { property: lastName }
                    prenom: { property: firstName }
                    # CoordinatesTrait
                    adresse: { property: address }
                    adresseComplete: { property: fullAddress }
                    codePostal: { property: zip }
                    ville: { property: city }
                    email: { property: email }
                    telephone: { property: phoneNumber }
                    # ProfessionalSituationTrait
                    public: { property: publicType.name }
                    categorie: { property: publicCategory.name }
                    service: { property: service }
                    fonction: { property: position }
                    payant: { property: isPaying }
                    # Trainee
                    inscriptions: { property: inscriptions }
            trainer:
                class: 'AppBundle\Entity\Trainer'
                excludeFromFormType: true
                alias: 'formateur'
                emailPath: 'email'
                fields:
                    #personTrait
                    civilite: { property: title }
                    nomComplet: { property: fullName }
                    nom: { property: lastName }
                    prenom: { property: firstName }
                    # CoordinatesTrait
                    adresse: { property: address }
                    adresseComplete: { property: fullAddress }
                    codePostal: { property: zip }
                    ville: { property: city }
                    email: { property: email }
                    telephone: { property: phoneNumber }
                    #coordinatesTrait
                    service: { property: service }
                    fonction: { property: position }
                    # other fields
                    sessions: { property: sessions }
            session:
                class: 'AppBundle\Entity\Session\Session'
                alias: 'session'
                fields:
                    # AbstractSession
                    nom: { property: "name" }
                    dateDebut: { property: "dateBegin", type: "date" }
                    dateDebutEnLettre: { property: "letterDateBegin", type: "date" }
                    dateFin: { property: "dateEnd", type: "date" }
                    dateFinEnLettre: { property: "letterDateEnd", type: "date" }
                    date: { property: "dateRange", type: "string" }
                    dateEnLettre: { property: "letterDateRange", type: "string" }
                    formation: { property: "training" }
                    formateurs: { property: "trainersListString" }
                    listeFormateurs: { property: "trainers" }
                    formateur: { property: "participations[0].trainer" }
                    nombrePlaces: { property: "maximumNumberOfRegistrations" }
                    nombreInscrits: { property: "numberOfRegistrations" }
                    dateLimiteInscription: { property: "limitRegistrationDate" }
                    datePrecisions: { property: "datePrecisions" }
                    nombreHeures: { property: "hourNumber" }
                    nombreJours: { property: "dayNumber" }
                    horaires: { property: "schedule" }
                    participantsMax: { property: "maximumNumberOfRegistrations" }
                    lieu: { property: "place.name" }
                    salle: { property: "room" }
                    adresse: { property: "place.fullAddress" }
                    #nombrePresents: { property: "numberOfPresentPeople" }
                    inscriptions: { property: "inscriptions" }
                    url: { property: "frontUrl" }
                    # Session
                    tarif: { property: "price" }
            training:
                class: 'SygeforCoreBundle:AbstractTraining'
                excludeFromFormType: true
                alias: 'formation'
                fields:
                    # Training
                    nom: { property: name }
                    theme: { property: theme.name}
                    centre: { property: organization }
                    numero: { property: number }
                    sessions: { property: sessions }
                    programme: { property: program, type: "ckeditor" }
                    objectifs: { property: description, type: "ckeditor" }
                    methodes: { property: teachingMethods, type: "ckeditor" }
                    gestionnaire: { property: user }
                    prerequis: { property: prerequisites }
                    publics: { property: publicTypes }
                    # Long training
                    module: { property: module.name }
                    # Meeting
                    national: { property: national, type: "boolean" }
            internship:
                class: 'AppBundle\Entity\Training\Internship'
                parent: training
            long_training:
                class: 'AppBundle\Entity\Training\LongTraining'
                parent: training
            meeting:
                class: 'AppBundle\Entity\Training\Meeting'
                parent: training
            semestered_training:
                class: 'Sygefor\Bundle\CoreBundle\Model\SemesteredTraining'
                alias: 'programme'
                fields:
                    annee: { property: year }
                    formation: { property: training}
                    sessions: { property: sessions}
                    semestre: { property: 'semester' }
                    intitule: { property: 'training.name' }
                    theme: { property: 'training.theme' }
                    nombreSessions: { property: 'sessionsCount' }
                    prochaineSession: { property: 'nextSession.dateBegin', type:'date', format: 'd/m/Y' }
                    derniereSession: { property: 'lastSession.dateBegin', type:'date', format: 'd/m/Y' }
            user:
                class: 'Sygefor\Bundle\CoreBundle\Entity\User'
                excludeFromFormType: true
                alias: 'gestionnaire'
                fields:
                    nom: { property: username }
                    email: { property: email }
        pdf:
            training:
                class: 'SygeforCoreBundle:AbstractTraining'
                template: 'training/pdf.html.twig'
                templateDiscriminator: 'type'
                templates:
                    internship: 'training/pdf/internship.html.twig'
                    long_training: 'training/pdf/long_training.html.twig'
                    meeting: 'training/pdf/meeting.html.twig'
            inscription.attestation:
                class: 'AppBundle\Entity\Inscription'
                template: 'inscription/attestation.pdf.twig'
                key: inscription
                filename: "attestation.pdf"
