imports:
    - { resource: elastica.yml }
    - { resource: batch_operation.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: notification.yml }
    - { resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml }

parameters:
    timezone: "Europe/Paris"
    router.request_context.scheme: "%scheme%"

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   "%trusted_hosts%"
    trusted_proxies: "%trusted_proxies%"
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: false

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - SygeforCoreBundle:Form:fields.html.twig
        - FrontBundle:Form:fields.html.twig
    date:
        timezone: "%timezone%"
    globals:
        app_name: "%app_name%"
        front_url: "%front_url%"
        publipost_document: "Publipostage.pdf"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false

# Doctrine extensions configuration
stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            tree: true
            timestampable: true

# Swiftmailer configuration
swiftmailer:
    default_mailer: default
    mailers:
        default:
            transport: "%mailer_transport%"
            encryption: "%mailer_encryption%"
            host:      "%mailer_host%"
            username:  "%mailer_user%"
            password:  "%mailer_password%"
            auth_mode: "%mailer_auth_mode%"
            port:      "%mailer_port%"
#            spool:
#                type: file
#                path: "%kernel.root_dir%/spool"
            spool:     { type: memory }

# SensionFrameworkExtra configuration
sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
#    request: { converters: true }

# Monolog configuration
monolog:
    channels: ["api", "batch_operation"]

# FOSRestBundle configuration
fos_rest:
    body_listener: true
    format_listener: false
#        rules:
#            - { path: '^/api/proxy.html', priorities: [html] }
#            - { path: '^/api', priorities: [json], fallback_format: json }
#            - { path: '^/', priorities: [json, html], fallback_format: json }
#    format_listener: true
    body_converter: { enabled: true }
    view:
        view_response_listener: true

jms_serializer:
    metadata:
        cache: file
        debug: "%kernel.debug%"
        auto_detection: true
        file_cache:
            dir: "%kernel.cache_dir%/serializer"
        directories:
            SygeforCoreBundle:
                namespace_prefix: Sygefor\Bundle\CoreBundle
                path: "@SygeforCoreBundle/Resources/config/serializer/sygeforuser"
            FOSUserBundle:
                namespace_prefix: FOS\CoreBundle
                path: "@SygeforCoreBundle/Resources/config/serializer/fosuser"

#MOPA
mopa_bootstrap:
    icons:
        icon_set: fontawesome4
    form:
#        render_required_asterisk: true
        render_optional_text: false
        horizontal: true
        horizontal_label_class:  col-sm-2 control-label
        horizontal_label_offset_class:  col-sm-offset-2
        horizontal_input_wrapper_class:  col-sm-10
        checkbox_label: both
    menu: ~  # enables twig helpers for menu

# FOS user configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Sygefor\Bundle\CoreBundle\Entity\User

# KnpSnappyBundle configuration
knp_snappy:
    pdf:
        enabled:    true
        binary:     "%wkhtmltopdf_bin%"
        options:    {encoding : 'utf8'}
