services:
    app.configure_menu_listener:
        class: AppBundle\EventListener\ConfigureMenuListener
        arguments:
            - "@security.context"
            - "@router"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_listener, event: sygefor_core.menu_configure, method: onMenuConfigure }
            - { name: kernel.event_listener, event: sygefor_core.menu_alter, method: onAlterConfigure }

    # Email CC resolvers
    app.email_resolver.trainer:
        class: AppBundle\Utils\EmailCCResolver\TraineeResolver
        tags:
            - { name: sygefor_core.email_resolver }
    notification.mailer:
        class: AppBundle\Utils\Mailer
        arguments: ["@mailer", "@twig", "%mailer.emails%", "@service_container"]
        public: true
        calls:
            - [ setSender, ["%mailer.sender_address%", "%mailer.sender_name%"] ]
